apiVersion: apps/v1
kind: Deployment
metadata:
  name: sar-warehouse

spec:
  replicas: 1
  selector:
    matchLabels:
      app: sar-warehouse
  template:
    metadata:
      labels:
        app: sar-warehouse
    spec:
      containers:
        - name: sar-warehouse
          image: ghcr.io/hernan940504/sar_ms_java:v1.0.0
          resources:
            requests:
              memory: "300Mi"
              cpu: "250m"
            limits:
              memory: "600Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
          securityContext:
            privileged: false

      restartPolicy: Always
