apiVersion: apps/v1
kind: Deployment
metadata:
  name: sar-core-ms

spec:
  replicas: 1
  selector:
    matchLabels:
      app: sar-core-ms
  template:
    metadata:
      labels:
        app: sar-core-ms
    spec:
      restartPolicy: Always
      containers:
        - name: sar-core-ms
          image: ghcr.io/joseesco24/sar_core_ms:v3.6.2
          resources:
            requests:
              memory: "300Mi"
              cpu: "250m"
            limits:
              memory: "600Mi"
              cpu: "500m"
          ports:
            - containerPort: 10048
          envFrom:
            - configMapRef:
                name: sar-core-ms-configmap
            - secretRef:
                name: sar-core-ms-secret
          securityContext:
            privileged: false
