apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sar-core-ms-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sar-core-ms
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 10
      policies:
        - type: Percent
          value: 60
          periodSeconds: 10
      selectPolicy: Min
    scaleDown:
      stabilizationWindowSeconds: 40
      policies:
        - type: Percent
          value: 80
          periodSeconds: 40
      selectPolicy: Min
